import type { Task } from "./types"
import { addDays, addHours, subDays, subHours } from "date-fns"

export const sampleTasks: Omit<Task, "id" | "createdAt" | "updatedAt">[] = [
  // High Priority Tasks
  {
    title: "Complete Final Project Presentation",
    description: "Prepare slides and practice presentation for Software Engineering course final project. Include architecture diagrams, code examples, and demo.",
    priority: "high",
    status: "in-progress",
    dueDate: addDays(new Date(), 2),
    category: "Assignment",
    tags: ["Presentation", "Software Engineering", "Final Project"],
    estimatedTime: 180,
    actualTime: 120,
    procrastinationFactor: 0.67,
    startedAt: subHours(new Date(), 2),
  },
  {
    title: "Study for Database Systems Midterm",
    description: "Review SQL queries, normalization, indexing, and transaction management. Practice with sample problems.",
    priority: "high",
    status: "todo",
    dueDate: addDays(new Date(), 1),
    category: "Exam",
    tags: ["Database", "Midterm", "Study"],
    estimatedTime: 240,
  },
  {
    title: "Submit Research Paper Draft",
    description: "Complete literature review section and submit first draft to professor for feedback.",
    priority: "high",
    status: "completed",
    dueDate: subDays(new Date(), 1),
    category: "Assignment",
    tags: ["Research", "Paper", "Literature Review"],
    estimatedTime: 300,
    actualTime: 420,
    procrastinationFactor: 1.4,
    completedAt: subHours(new Date(), 5),
  },

  // Medium Priority Tasks
  {
    title: "Group Meeting - Mobile App Project",
    description: "Discuss UI/UX design decisions and assign tasks for next sprint. Review current progress and blockers.",
    priority: "medium",
    status: "todo",
    dueDate: addDays(new Date(), 3),
    category: "Meeting",
    tags: ["Group Work", "Mobile App", "UI/UX"],
    estimatedTime: 90,
  },
  {
    title: "Update LinkedIn Profile",
    description: "Add recent projects, update skills, and write a compelling summary for internship applications.",
    priority: "medium",
    status: "in-progress",
    dueDate: addDays(new Date(), 5),
    category: "Personal",
    tags: ["Career", "LinkedIn", "Internship"],
    estimatedTime: 60,
    actualTime: 30,
    procrastinationFactor: 0.5,
    startedAt: subHours(new Date(), 1),
  },
  {
    title: "Read Chapter 8 - Algorithms Textbook",
    description: "Study dynamic programming concepts and solve practice problems at the end of the chapter.",
    priority: "medium",
    status: "todo",
    dueDate: addDays(new Date(), 4),
    category: "Study",
    tags: ["Algorithms", "Dynamic Programming", "Reading"],
    estimatedTime: 120,
  },
  {
    title: "Prepare for Internship Interview",
    description: "Research company background, practice common technical questions, and prepare questions to ask interviewer.",
    priority: "medium",
    status: "todo",
    dueDate: addDays(new Date(), 6),
    category: "Career",
    tags: ["Interview", "Internship", "Preparation"],
    estimatedTime: 150,
  },
  {
    title: "Complete Lab Assignment 5",
    description: "Implement binary search tree operations and test with provided test cases.",
    priority: "medium",
    status: "completed",
    dueDate: subDays(new Date(), 2),
    category: "Assignment",
    tags: ["Data Structures", "Binary Tree", "Lab"],
    estimatedTime: 90,
    actualTime: 75,
    procrastinationFactor: 0.83,
    completedAt: subHours(new Date(), 8),
  },

  // Low Priority Tasks
  {
    title: "Organize Study Notes",
    description: "Sort and categorize notes from all courses, create digital backups, and organize by subject.",
    priority: "low",
    status: "todo",
    dueDate: addDays(new Date(), 10),
    category: "Personal",
    tags: ["Organization", "Notes", "Study"],
    estimatedTime: 120,
  },
  {
    title: "Learn React Hooks",
    description: "Complete online tutorial on React hooks (useState, useEffect, useContext) and build a small practice project.",
    priority: "low",
    status: "todo",
    dueDate: addDays(new Date(), 14),
    category: "Study",
    tags: ["React", "JavaScript", "Web Development"],
    estimatedTime: 180,
  },
  {
    title: "Update Portfolio Website",
    description: "Add recent projects, improve responsive design, and optimize loading speed.",
    priority: "low",
    status: "todo",
    dueDate: addDays(new Date(), 12),
    category: "Personal",
    tags: ["Portfolio", "Web Development", "Design"],
    estimatedTime: 240,
  },
  {
    title: "Research Graduate School Programs",
    description: "Look into CS graduate programs, compare curriculum, and note application requirements and deadlines.",
    priority: "low",
    status: "todo",
    dueDate: addDays(new Date(), 20),
    category: "Career",
    tags: ["Graduate School", "Research", "Planning"],
    estimatedTime: 300,
  },

  // Overdue Tasks
  {
    title: "Submit Homework 3 - Machine Learning",
    description: "Complete exercises on linear regression and submit before deadline.",
    priority: "high",
    status: "todo",
    dueDate: subDays(new Date(), 1),
    category: "Assignment",
    tags: ["Machine Learning", "Linear Regression", "Homework"],
    estimatedTime: 120,
  },
  {
    title: "Attend Career Fair Preparation Workshop",
    description: "Learn about networking strategies and resume tips for upcoming career fair.",
    priority: "medium",
    status: "completed",
    dueDate: subDays(new Date(), 3),
    category: "Career",
    tags: ["Career Fair", "Networking", "Workshop"],
    estimatedTime: 60,
    actualTime: 60,
    procrastinationFactor: 1.0,
    completedAt: subDays(new Date(), 3),
  },

  // Additional Tasks for 20+ count
  {
    title: "Review Code for Team Project",
    description: "Code review for teammate's pull request, test functionality, and provide feedback.",
    priority: "medium",
    status: "in-progress",
    dueDate: addDays(new Date(), 2),
    category: "Assignment",
    tags: ["Code Review", "Team Work", "Git"],
    estimatedTime: 45,
    actualTime: 20,
    procrastinationFactor: 0.44,
    startedAt: subHours(new Date(), 1),
  },
  {
    title: "Practice LeetCode Problems",
    description: "Solve 3 medium difficulty problems focusing on array and string manipulation.",
    priority: "low",
    status: "todo",
    dueDate: addDays(new Date(), 7),
    category: "Study",
    tags: ["LeetCode", "Coding Practice", "Algorithms"],
    estimatedTime: 90,
  },
  {
    title: "Backup Important Files",
    description: "Create backup of project files, documents, and photos to cloud storage.",
    priority: "low",
    status: "todo",
    dueDate: addDays(new Date(), 8),
    category: "Personal",
    tags: ["Backup", "Cloud Storage", "Organization"],
    estimatedTime: 60,
  },
  {
    title: "Plan Study Schedule for Finals",
    description: "Create detailed study plan for upcoming final exams, allocate time for each subject.",
    priority: "medium",
    status: "todo",
    dueDate: addDays(new Date(), 5),
    category: "Study",
    tags: ["Planning", "Finals", "Schedule"],
    estimatedTime: 30,
  },
  {
    title: "Complete Online Course Module",
    description: "Finish Module 4 of 'Introduction to Data Science' course on Coursera.",
    priority: "low",
    status: "completed",
    dueDate: subDays(new Date(), 2),
    category: "Study",
    tags: ["Online Course", "Data Science", "Coursera"],
    estimatedTime: 120,
    actualTime: 150,
    procrastinationFactor: 1.25,
    completedAt: subHours(new Date(), 12),
  },
  {
    title: "Update Resume for Summer Internships",
    description: "Add recent projects and achievements, tailor for software engineering internships.",
    priority: "medium",
    status: "todo",
    dueDate: addDays(new Date(), 4),
    category: "Career",
    tags: ["Resume", "Internship", "Software Engineering"],
    estimatedTime: 75,
  },
  {
    title: "Research Part-time Job Opportunities",
    description: "Look for part-time programming or tutoring positions for next semester.",
    priority: "low",
    status: "todo",
    dueDate: addDays(new Date(), 15),
    category: "Career",
    tags: ["Part-time Job", "Research", "Income"],
    estimatedTime: 90,
  },
  {
    title: "Organize Digital Workspace",
    description: "Clean up desktop, organize folders, and set up development environment shortcuts.",
    priority: "low",
    status: "completed",
    dueDate: subDays(new Date(), 5),
    category: "Personal",
    tags: ["Organization", "Workspace", "Productivity"],
    estimatedTime: 45,
    actualTime: 60,
    procrastinationFactor: 1.33,
    completedAt: subDays(new Date(), 5),
  },
  {
    title: "Practice Presentation Skills",
    description: "Record practice presentation and work on public speaking confidence.",
    priority: "medium",
    status: "todo",
    dueDate: addDays(new Date(), 6),
    category: "Personal",
    tags: ["Presentation", "Public Speaking", "Practice"],
    estimatedTime: 60,
  },
  {
    title: "Learn Git Advanced Features",
    description: "Study Git branching strategies, rebasing, and collaboration workflows.",
    priority: "low",
    status: "todo",
    dueDate: addDays(new Date(), 18),
    category: "Study",
    tags: ["Git", "Version Control", "Collaboration"],
    estimatedTime: 120,
  },
  {
    title: "Plan Weekend Study Group",
    description: "Coordinate with classmates for weekend study session before midterms.",
    priority: "medium",
    status: "in-progress",
    dueDate: addDays(new Date(), 1),
    category: "Study",
    tags: ["Study Group", "Collaboration", "Midterms"],
    estimatedTime: 30,
    actualTime: 15,
    procrastinationFactor: 0.5,
    startedAt: subHours(new Date(), 1),
  },
  {
    title: "Review Calculus Concepts",
    description: "Go through calculus review problems to prepare for upcoming math course.",
    priority: "low",
    status: "todo",
    dueDate: addDays(new Date(), 16),
    category: "Study",
    tags: ["Calculus", "Math", "Review"],
    estimatedTime: 150,
  },
  {
    title: "Set Up Development Environment",
    description: "Install and configure VS Code extensions, Git, Node.js, and other development tools.",
    priority: "medium",
    status: "completed",
    dueDate: subDays(new Date(), 7),
    category: "Personal",
    tags: ["Development", "Setup", "Tools"],
    estimatedTime: 90,
    actualTime: 120,
    procrastinationFactor: 1.33,
    completedAt: subDays(new Date(), 7),
  },
  {
    title: "Write Blog Post About Learning Journey",
    description: "Document experiences and lessons learned during the semester for personal blog.",
    priority: "low",
    status: "todo",
    dueDate: addDays(new Date(), 25),
    category: "Personal",
    tags: ["Blog", "Writing", "Reflection"],
    estimatedTime: 180,
  },
]

export function initializeSampleData(): void {
  const existingTasks = localStorage.getItem("anyf-time-manager-tasks")
  if (!existingTasks || JSON.parse(existingTasks).length === 0) {
    const tasksWithIds = sampleTasks.map((task) => ({
      ...task,
      id: crypto.randomUUID(),
      createdAt: new Date(),
      updatedAt: new Date(),
    }))
    localStorage.setItem("anyf-time-manager-tasks", JSON.stringify(tasksWithIds))
  }
}
